# Generated by Django 2.2.5 on 2020-06-07 01:26

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Indicates the date on which the model was created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Indicates the date it was last updated', null=True)),
                ('hash', models.CharField(default='', editable=False, help_text='Unique identifier to identify the state of the model', max_length=32, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': '_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Indicates the date on which the model was created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Indicates the date it was last updated', null=True)),
                ('hash', models.CharField(default='', editable=False, help_text='Unique identifier to identify the state of the model', max_length=32, null=True)),
                ('name', models.CharField(choices=[('SALUD', 'salud'), ('ENTRETENIMIENTO', 'entretenimiento'), ('ABARROTES', 'abarrotes'), ('CUIDADO PERSONAL', 'cuidado personal'), ('BELLEZA', 'belleza'), ('ACTIVIDAD FISICA', 'actividad fisica'), ('CONSTRUCCION Y MANTENIMIENTO', 'construccion y mantenimiento'), ('TRANSPORTE', 'transporte'), ('RESTAURANTES', 'restaurantes'), ('COMIDA', 'comida'), ('CONTRATISTAS', 'contratistas')], max_length=64)),
            ],
            options={
                'db_table': '_category',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Indicates the date on which the model was created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Indicates the date it was last updated', null=True)),
                ('hash', models.CharField(default='', editable=False, help_text='Unique identifier to identify the state of the model', max_length=32, null=True)),
                ('url', models.URLField(help_text='File reference link (eg. http://localhost:8000/image.png)', max_length=1024)),
                ('size', models.IntegerField(help_text='File size in bytes')),
                ('name', models.CharField(help_text='Common File Name (eg. Image.png)', max_length=1024)),
            ],
            options={
                'db_table': 'file',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Indicates the date on which the model was created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Indicates the date it was last updated', null=True)),
                ('hash', models.CharField(default='', editable=False, help_text='Unique identifier to identify the state of the model', max_length=32, null=True)),
                ('name', models.CharField(choices=[('OWNER', 'OWNER'), ('CLIENT', 'CLIENT')], max_length=64)),
            ],
            options={
                'db_table': '_user_type',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Indicates the date on which the model was created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Indicates the date it was last updated', null=True)),
                ('hash', models.CharField(default='', editable=False, help_text='Unique identifier to identify the state of the model', max_length=32, null=True)),
                ('prop_1', models.IntegerField(default=0)),
                ('prop_2', models.IntegerField(default=0)),
                ('prop_3', models.IntegerField(default=0)),
                ('prop_4', models.IntegerField(default=0)),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '_stat',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Indicates the date on which the model was created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Indicates the date it was last updated', null=True)),
                ('hash', models.CharField(default='', editable=False, help_text='Unique identifier to identify the state of the model', max_length=32, null=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('address_cords', models.CharField(blank=True, max_length=512)),
                ('contact_1', models.CharField(blank=True, max_length=250)),
                ('contact_2', models.CharField(blank=True, max_length=250)),
                ('contact_3', models.CharField(blank=True, max_length=250)),
                ('contact_4', models.CharField(blank=True, max_length=250)),
                ('tags', models.TextField(blank=True)),
                ('is_local', models.BooleanField(default=False)),
                ('opening_time', models.DateTimeField(default=datetime.datetime.now)),
                ('closing_time', models.DateTimeField(default=datetime.datetime.now)),
                ('open_days', models.CharField(blank=True, max_length=50)),
                ('verified', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='models.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '_business',
            },
        ),
    ]
